(()=>{
const BUCKET='rmc-documents';
function ensurePdfLib(){if(window.jspdf)return Promise.resolve();return new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/jspdf@2.5.2/dist/jspdf.umd.min.js';s.onload=ok;s.onerror=()=>no(new Error('No se pudo cargar el generador PDF'));document.head.appendChild(s)})}
async function logoData(){if(window._rmcLogoData)return window._rmcLogoData;try{const r=await fetch('./rmc-logo.jpg',{cache:'no-store'}),b=await r.blob();window._rmcLogoData=await new Promise((ok,no)=>{const fr=new FileReader();fr.onload=()=>ok(fr.result);fr.onerror=no;fr.readAsDataURL(b)});return window._rmcLogoData}catch(e){return null}}
function displayType(t){return t==='ALBARAN'?'ALBARÁN':t}
async function pdfFromSnapshot(x){await ensurePdfLib();const{jsPDF}=window.jspdf,d=new jsPDF({unit:'mm',format:'a4'}),navy=[6,41,104],orange=[255,81,8],line=[203,212,226],kind=displayType(x.doc_type);d.setFillColor(...navy);d.rect(0,0,122,7,'F');d.setFillColor(...orange);d.rect(122,0,88,7,'F');const logo=await logoData();if(logo){try{d.addImage(logo,'JPEG',15,16,86,27)}catch(e){}}d.setTextColor(...navy);d.setFont('helvetica','bold');d.setFontSize(kind==='PRESUPUESTO'?26:(kind==='ALBARÁN'?25:34));d.text(kind,116,25);d.setDrawColor(...orange);d.setLineWidth(1.2);d.line(116,30,145,30);d.setFontSize(10);d.text(`Nº ${x.number||''}`,116,38);d.setFont('helvetica','normal');d.text(`Fecha: ${dateES(x.doc_date)}`,116,45);d.setDrawColor(...navy);d.setLineWidth(.4);d.line(104,55,104,89);d.setFont('helvetica','bold');d.setFontSize(11);d.text('EMISOR',20,58);d.text('CLIENTE',116,58);d.setDrawColor(...orange);d.setLineWidth(.8);d.line(20,61,42,61);d.line(116,61,140,61);d.setFont('helvetica','normal');d.setFontSize(9);['Rodrigo Monte Costantin','NIF: 06660591K','C/ Ocaña, 189','28047 - Madrid','Tel. 677 109 844'].forEach((t,i)=>d.text(t,20,68+i*5));[x.client_name||'',x.client_tax?`CIF/NIF: ${x.client_tax}`:'',x.client_address||'',[x.client_zip,x.client_city].filter(Boolean).join(' - '),x.client_phone?`Tel. ${x.client_phone}`:'',x.client_email||''].filter(Boolean).forEach((t,i)=>d.text(String(t).slice(0,48),116,68+i*5));d.setFillColor(...navy);d.rect(17,103,176,10,'F');d.setTextColor(255);d.setFont('helvetica','bold');d.setFontSize(9);d.text('CONCEPTO',21,109.5);d.text('IMPORTE',166,109.5);let y=122;d.setTextColor(25);d.setFont('helvetica','normal');for(const it of (x.items||[])){const lines=d.splitTextToSize(it.concept||'',137);d.text(lines,21,y);d.text(money(it.amount),166,y);y+=Math.max(8,lines.length*5+3)}y=Math.max(y+5,165);const rows=[['BASE IMPONIBLE',x.base_total],[`IVA (${String(x.vat_rate||0).replace('.',',')} %)`,x.vat_total]];if(Number(x.advance||0)>0)rows.push(['ANTICIPO',-Number(x.advance)]);rows.push([`TOTAL ${kind}`,x.grand_total]);rows.forEach((r,i)=>{d.setFillColor(...navy);d.rect(107,y+i*10,51,10,'F');d.setTextColor(255);d.setFont('helvetica','bold');d.text(r[0],109,y+6.5+i*10);if(i===rows.length-1)d.setFillColor(...orange);else d.setFillColor(255,255,255);d.rect(158,y+i*10,35,10,'F');d.setTextColor(i===rows.length-1?255:20);d.text(money(r[1]),161,y+6.5+i*10)});d.setDrawColor(...navy);d.setLineWidth(.55);d.line(10,270,200,270);d.setFontSize(7);d.setTextColor(...orange);d.setFont('helvetica','bold');d.text('EMPRESA AUTORIZADA',14,277);d.setTextColor(...navy);d.setFont('helvetica','normal');d.text('Empresa instaladora y mantenedora autorizada por la Comunidad de Madrid y habilitada para la manipulación de gases fluorados.',14,282,{maxWidth:95});d.setFont('helvetica','bold');d.setTextColor(...orange);d.text('CONTACTO WHATSAPP',143,277);d.setTextColor(...navy);d.setFont('helvetica','normal');d.text('677 109 844',159,282);return d}
async function upload(blob,type,number){const safe=String(number||Date.now()).replace(/[^A-Za-z0-9._-]/g,'_'),year=(String(number||'').match(/20\d{2}/)||[new Date().getFullYear()])[0],folder=type==='FACTURA'?'facturas':type==='PRESUPUESTO'?'presupuestos':'albaranes',path=`${folder}/${year}/${safe}_${Date.now()}.pdf`;const{error}=await sb.storage.from(BUCKET).upload(path,blob,{contentType:'application/pdf',upsert:false});if(error)throw error;return path}
window.openCloudDocument=async path=>{if(!path)return;const{data,error}=await sb.storage.from(BUCKET).createSignedUrl(path,3600);if(error){alert(error.message);return}window.open(data.signedUrl,'_blank')};
const typeSel=document.getElementById('docType');if(typeSel&&!Array.from(typeSel.options).some(o=>o.value==='ALBARAN')){const o=document.createElement('option');o.value='ALBARAN';o.textContent='ALBARÁN';typeSel.appendChild(o)}
const city=document.getElementById('clientCity');if(city&&!document.getElementById('clientPhone')){const wrap=document.createElement('div');wrap.className='row';wrap.innerHTML='<div><label>Teléfono</label><input id="clientPhone" type="tel"></div><div><label>Email</label><input id="clientEmail" type="email"></div>';city.parentNode.insertBefore(wrap,city.nextSibling)}
const css=document.createElement('style');css.textContent='.cloudtag{font-size:10px;color:#167a45;font-weight:bold}.hist .docbuttons{display:flex;gap:5px;align-items:center}.dh h2.albaran{font-size:9.5mm;letter-spacing:-.15mm;margin-top:5mm}';document.head.appendChild(css);
const oldUpdate=update;update=function(){oldUpdate();const t=$('docType').value;$('pType').textContent=displayType(t);$('pType').classList.toggle('albaran',t==='ALBARAN')};
suggestNumber=async function(){const type=$('docType').value,{data}=await sb.from('rmc_documents').select('number').eq('doc_type',type).order('id',{ascending:false}).limit(1);if(data&&data.length)$('number').value=increment(data[0].number);else $('number').value=type==='FACTURA'?'2026-07-0008':type==='PRESUPUESTO'?'2026-0090':`ALB-${new Date().getFullYear()}-00001`;update()};
saveDocument=async function(){if(!user)return;const wasCurrent=!!currentId;['clientName','clientAddress','clientCity'].forEach(id=>$(id).value=smart($(id).value));$('clientTax').value=tax($('clientTax').value);items=items.map(x=>({concept:smart(x.concept),amount:num(x.amount)}));const z=totals(),payload={user_id:user.id,doc_type:$('docType').value,number:$('number').value.trim().toUpperCase(),doc_date:$('date').value,client_name:$('clientName').value,client_tax:$('clientTax').value,client_zip:$('clientZip').value,client_address:$('clientAddress').value,client_city:$('clientCity').value,client_phone:$('clientPhone')?.value.trim()||null,client_email:$('clientEmail')?.value.trim()||null,vat_rate:z.vr,advance:z.ad,items,base_total:z.base,vat_total:z.va,grand_total:z.total};$('status').textContent='Guardando documento y PDF en RMC Cloud…';let q=currentId?sb.from('rmc_documents').update(payload).eq('id',currentId).select('*').single():sb.from('rmc_documents').insert(payload).select('*').single(),{data:row,error}=await q;if(error){$('status').textContent='No se pudo guardar: '+error.message;return}try{const pdf=await pdfFromSnapshot(payload),blob=pdf.output('blob'),path=await upload(blob,payload.doc_type,payload.number);await sb.from('rmc_documents').update({pdf_path:path}).eq('id',row.id);$('status').innerHTML='Documento y PDF guardados en <b>RMC Cloud</b>.'}catch(e){$('status').textContent='Datos guardados, pero el PDF no se pudo subir: '+e.message}await loadHistory();if(!wasCurrent)await suggestNumber()};
loadHistory=async function(){if(!user)return;const{data,error}=await sb.from('rmc_documents').select('*').order('doc_date',{ascending:false}).order('id',{ascending:false}).limit(80);if(error){$('status').textContent=error.message;return}$('history').innerHTML=(data||[]).map(d=>`<div class="hist"><div><b>${displayType(d.doc_type)} ${d.number}</b><br>${d.client_name||''} · ${money(d.grand_total)}${d.pdf_path?'<br><span class="cloudtag">● PDF en RMC Cloud</span>':''}</div><div class="docbuttons"><button class="g" onclick='openDoc(${JSON.stringify(d)})'>Abrir</button>${d.pdf_path?`<button class="p" onclick="openCloudDocument('${String(d.pdf_path).replace(/'/g,"\\'")}')">PDF nube</button>`:''}</div></div>`).join('')};
const oldOpen=openDoc;openDoc=function(d){oldOpen(d);if($('clientPhone'))$('clientPhone').value=d.client_phone||'';if($('clientEmail'))$('clientEmail').value=d.client_email||'';update()};
typeSel?.addEventListener('change',()=>{suggestNumber()});
setTimeout(()=>{update();loadHistory()},100);
})();
